name: admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  fl_chart: ^0.64.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0

  path_provider: ^2.1.2
  image: ^4.1.3



  # Tambahan untuk API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Tambahan untuk generator
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.svg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/example.png
    - assets/images/logo.png